name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: ministryofjustice/github-actions/code-formatter@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
