name: code-formatter

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: ministryofjustice/github-actions/code-formatter@v14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
