name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 10:20 UTC
    - cron: '20 10 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      - uses: ministryofjustice/modernisation-platform-incident-response@latest
