name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 10:20 UTC
    - cron: '20 10 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: ministryofjustice/modernisation-platform-incident-response@latest
