name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every Tuesday, at 10:20 UTC
    - cron: '20 10 * * 2'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: ministryofjustice/modernisation-platform-incident-response@latest
